[lib]
name = "brp"
path = "src/lib.rs"

[package]
name = "brp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "*"
strum = "*"
strum_macros = "*"